# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  ci:
    desc: Run all CI tasks
    cmds:
      - task deps
      # - task lint
      - task test
      - task build

  deps:
    desc: Install project dependencies
    cmd: go mod download

  run:
    desc: Run the project
    cmd: go run ./cmd/aiquota

  build:
    desc: Build the project
    cmd: go build -o ./dist/aiquota ./cmd/aiquota

  format:
    desc: Format the code
    cmds:
      - go fmt ./...
      - dprint fmt

  test:
    desc: Run tests
    cmd: go test -v ./...

  lint:
    desc: Lint the code
    cmds:
      - dprint check
      - golangci-lint run

  # Cross-compilation targets for release builds
  build:all:
    desc: Build binaries for all supported platforms
    cmds:
      - task: build:linux-amd64
      - task: build:linux-arm64
      - task: build:darwin-amd64
      - task: build:darwin-arm64
      - task: build:windows-amd64
      - task: build:windows-arm64
      - task: build:checksums

  build:linux-amd64:
    desc: Build for Linux AMD64
    cmd: >-
      CGO_ENABLED=0 GOOS=linux GOARCH=amd64
      go build -ldflags "-s -w" -o dist/aiquota-linux-amd64 ./cmd/aiquota/.

  build:linux-arm64:
    desc: Build for Linux ARM64
    cmd: >-
      CGO_ENABLED=0 GOOS=linux GOARCH=arm64
      go build -ldflags "-s -w" -o dist/aiquota-linux-arm64 ./cmd/aiquota/.

  build:darwin-amd64:
    desc: Build for macOS AMD64
    cmd: >-
      CGO_ENABLED=0 GOOS=darwin GOARCH=amd64
      go build -ldflags "-s -w" -o dist/aiquota-darwin-amd64 ./cmd/aiquota/.

  build:darwin-arm64:
    desc: Build for macOS ARM64 (Apple Silicon)
    cmd: >-
      CGO_ENABLED=0 GOOS=darwin GOARCH=arm64
      go build -ldflags "-s -w" -o dist/aiquota-darwin-arm64 ./cmd/aiquota/.

  build:windows-amd64:
    desc: Build for Windows AMD64
    cmd: >-
      CGO_ENABLED=0 GOOS=windows GOARCH=amd64
      go build -ldflags "-s -w" -o dist/aiquota-windows-amd64.exe ./cmd/aiquota/.

  build:windows-arm64:
    desc: Build for Windows ARM64
    cmd: >-
      CGO_ENABLED=0 GOOS=windows GOARCH=arm64
      go build -ldflags "-s -w" -o dist/aiquota-windows-arm64.exe ./cmd/aiquota/.

  build:checksums:
    desc: Generate checksums for all binaries in dist/
    cmd: cd dist && sha256sum aiquota-* > checksums.txt
